### ISSUE TITLE
Error running social-distance

### ISSUE THREAD

**Issue by ticlazau** [neuralet/neuralet#44]
Hello, 

I am trying to run the social-distance like this:

docker run -it --runtime nvidia --privileged -p 8000:8000 -v /data/projects/neuralet:/repo neuralet/jetson-nano:applications-smart-distancing

But I am getting this error:

`Traceback (most recent call last):
  File "neuralet-distancing.py", line 22, in <module>
    DistanceApp(args)
  File "neuralet-distancing.py", line 13, in __init__
    self.engine = CvEngine(self.config)
  File "/repo/applications/smart-distancing/libs/core.py", line 19, in __init__
    self.logger = Logger(self.config)
  File "/repo/applications/smart-distancing/libs/loggers/loggers.py", line 19, in __init__
    self.name = self.config.get_section_dict("Logger")["Name"]
  File "/repo/applications/smart-distancing/libs/config_engine.py", line 59, in get_section_dict
    return self.section_options_dict[section]
KeyError: 'Logger'`

Same issue if I run inside the container the neuralet-distancing.py:

`root@5ad09acb184a:/repo/applications/smart-distancing# python3 neuralet-distancing.py --config config-jetson.ini 
Traceback (most recent call last):
  File "neuralet-distancing.py", line 22, in <module>
    DistanceApp(args)
  File "neuralet-distancing.py", line 13, in __init__
    self.engine = CvEngine(self.config)
  File "/repo/applications/smart-distancing/libs/core.py", line 19, in __init__
    self.logger = Logger(self.config)
  File "/repo/applications/smart-distancing/libs/loggers/loggers.py", line 19, in __init__
    self.name = self.config.get_section_dict("Logger")["Name"]
  File "/repo/applications/smart-distancing/libs/config_engine.py", line 59, in get_section_dict
    return self.section_options_dict[section]
KeyError: 'Logger'`

Any ideas how I can overcome this issue?

Thank you,
FM

**Comment by SaddamBInSyed** [comment]
Hi.

App trying to find 'Logger' field in the config file but it couldn't.

You can find the same on another ' config- skeleton.ini file ' and paste into the condig-jetson file.


Hope this helps.

**Comment by alpha-carinae29** [comment]
Hi @ticlazau , thanks for your feedback, as @SaddamBInSyed mentioned you should copy:
```
[Logger]
Name: csv_logger
TimeInterval: 0.5
LogDirectory: /repo/applications/smart-distancing/ui/static/data
```
to the bottom of the `config-jetson.ini` file

**Comment by ticlazau** [comment]
Thank you! 
all good now, I am able to start and run the video example.

Rgds
FM

PS: with other videos social distance is not working, event with two persons in the video

**Comment by alpha-carinae29** [comment]
@ticlazau would you please open another issue and describe the problem with other video with more details?
Tnx
