### ISSUE TITLE
Trying deploy on Nano and I am getting file not found error

### ISSUE THREAD

**Issue by BalajiNJL** [neuralet/neuralet#79]
I am trying run this on Nano and I am getting the following error

docker run -it --runtime nvidia --privileged -p 8000:8000 -v /home/nano/neuralet/:/repo neuralet/jetson-nano:applications-smart-distancing
[TensorRT] ERROR: Could not register plugin creator:  FlattenConcat_TRT in namespace:
Traceback (most recent call last):
  File "neuralet-distancing.py", line 22, in <module>
    DistanceApp(args)
  File "neuralet-distancing.py", line 13, in __init__
    self.engine = CvEngine(self.config)
  File "/repo/applications/smart-distancing/libs/core.py", line 23, in __init__
    self.detector = Detector(self.config)
  File "/repo/applications/smart-distancing/libs/detectors/jetson/detector.py", line 18, in __init__
    self.net = mobilenet_ssd_v2.Detector(self.config)
  File "/repo/applications/smart-distancing/libs/detectors/jetson/mobilenet_ssd_v2.py", line 57, in __init__
    self.engine = self._load_engine()
  File "/repo/applications/smart-distancing/libs/detectors/jetson/mobilenet_ssd_v2.py", line 26, in _load_engine
    with open(trt_bin_path, 'rb') as f, trt.Runtime(self.trt_logger) as runtime:
FileNotFoundError: [Errno 2] No such file or directory: 'libs/detectors/jetson/data/TRT_ssd_mobilenet_v2_coco.bin'
Exception ignored in: <bound method Detector.__del__ of <libs.detectors.jetson.mobilenet_ssd_v2.Detector object at 0x7f9c64c080>>
Traceback (most recent call last):
  File "/repo/applications/smart-distancing/libs/detectors/jetson/mobilenet_ssd_v2.py", line 70, in __del__
    del self.stream
AttributeError: stream

I checked and I see no files in data folder
@jetson-nano:~/neuralet/applications/smart-distancing/libs/detectors/jetson$ cd data
@jetson-nano:~/neuralet/applications/smart-distancing/libs/detectors/jetson/data$ ls
@jetson-nano:~/neuralet/applications/smart-distancing/libs/detectors/jetson/data$

From where I can d/l TRT_ssd_mobilenet_v2_coco.bin.

**Comment by BalajiNJL** [comment]
NM, i re-ran download_jetson_trt.sh and it worked.
