### ISSUE TITLE
Exception on frames without objects

### ISSUE THREAD

**Issue by mohammad7t** [neuralet/neuralet#84]
**Describe the bug**
The following error is raised when a frame without object is given:
```
Traceback (most recent call last):
  File "neuralet-distancing.py", line 22, in <module>
    DistanceApp(args)
  File "neuralet-distancing.py", line 16, in __init__
    self.ui.start()
  File "/repo/applications/smart-distancing/ui/web_gui.py", line 191, in start
    self.__ENGINE_INSTANCE.process_video(video_path)
  File "/repo/applications/smart-distancing/libs/core.py", line 94, in process_video
    self.logger.update(objects, distancings)
  File "/repo/applications/smart-distancing/libs/loggers/loggers.py", line 48, in update
    self.logger.update(objects_list, distances)
  File "/repo/applications/smart-distancing/libs/loggers/csv_processed_logger.py", line 43, in update
    self.log_objects(objects_list, distances, objects_log_file_path)
  File "/repo/applications/smart-distancing/libs/loggers/csv_processed_logger.py", line 57, in log_objects
    violating_objects = extract_violating_objects(distances, self.dist_threshold)
  File "/repo/applications/smart-distancing/tools/objects_post_process.py", line 18, in extract_violating_objects
    triu_distances = np.triu(distances) + np.tril((float(dist_threshold) + 1) * np.ones(distances.shape))
  File "<__array_function__ internals>", line 6, in triu
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/twodim_base.py", line 465, in triu
    mask = tri(*m.shape[-2:], k=k-1, dtype=bool)
TypeError: tri() missing 1 required positional argument: 'N'
```

**To Reproduce**
Use dummy detector with default config on x86

**Comment by mohammad7t** [comment]
It turns out the problem was not with zero objects, but with `None` in https://github.com/neuralet/neuralet/blob/8b1d6fb811225dcdf4485074c1897741445e6d5c/applications/smart-distancing/libs/core.py#L52
